site_name: My Docs Site
theme:
  name: material
  features:
    - content.code.copy  # Enables the copy button for all code blocks
    # Optional: Add these for enhanced code features
    - content.code.annotate  # For code annotations
    - content.code.select    # For line selection in code blocks
nav:
  - Home: index.md
  - SSL Certificate Renewal: ssl_certificate_renewal_instructions.md
  - Control-M Standards and Job Setup Guide: control-m_standards.md
plugins:
  - minify
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences